// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbjBUcNR1GfikXun2dfsVgpPPmJMohBmc',
    appId: '1:46967837061:web:7a85bd5501994841a5b4ec',
    messagingSenderId: '46967837061',
    projectId: 'proyecto-43391',
    authDomain: 'proyecto-43391.firebaseapp.com',
    databaseURL: 'https://proyecto-43391-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-43391.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmJpKVKmEXdnh6RRR8R3xK8JQQJVI_-k',
    appId: '1:46967837061:android:9f03372ab2729293a5b4ec',
    messagingSenderId: '46967837061',
    projectId: 'proyecto-43391',
    databaseURL: 'https://proyecto-43391-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-43391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweEp9uV5mI8c3DZy0YVqei3NfhgxbRiY',
    appId: '1:46967837061:ios:fd820759af143ef1a5b4ec',
    messagingSenderId: '46967837061',
    projectId: 'proyecto-43391',
    databaseURL: 'https://proyecto-43391-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-43391.appspot.com',
    androidClientId:
        '46967837061-aupgjmd1gvg7ldsm2knjobi9pq809bst.apps.googleusercontent.com',
    iosClientId:
        '46967837061-a823rtr0gd8ggm2e1jd6kcfehrr41jvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCweEp9uV5mI8c3DZy0YVqei3NfhgxbRiY',
    appId: '1:46967837061:ios:fd820759af143ef1a5b4ec',
    messagingSenderId: '46967837061',
    projectId: 'proyecto-43391',
    databaseURL: 'https://proyecto-43391-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-43391.appspot.com',
    androidClientId:
        '46967837061-aupgjmd1gvg7ldsm2knjobi9pq809bst.apps.googleusercontent.com',
    iosClientId:
        '46967837061-a823rtr0gd8ggm2e1jd6kcfehrr41jvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutter',
  );
}
